# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#

templates:
  params:
    author-email: "andrewk36@gmail.com"
    author-name: "Andrew Kennedy"
    github-username: "andrew-kennedy"
